// File generated by FlutterFire CLI and adapted to keep Firebase config
// available without bundling runtime dotenv secrets.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmLnlJig_nx0ihDAgmvChclKJinQk1gFo',
    appId: '1:686491556501:web:01f6df547bd2aa1e14999c',
    messagingSenderId: '686491556501',
    projectId: 'foodcal-b63fc',
    authDomain: 'foodcal-b63fc.firebaseapp.com',
    storageBucket: 'foodcal-b63fc.firebasestorage.app',
    measurementId: 'G-PCDJRSMMKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqjlecc0VfwFVdEdOmn59aXSSkl68K7EE',
    appId: '1:686491556501:android:5566934458b9f14814999c',
    messagingSenderId: '686491556501',
    projectId: 'foodcal-b63fc',
    storageBucket: 'foodcal-b63fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHKmrukjgVAd5lM2smEdmGqSl-RtOcA2U',
    appId: '1:686491556501:ios:05e59c92165a8de814999c',
    messagingSenderId: '686491556501',
    projectId: 'foodcal-b63fc',
    storageBucket: 'foodcal-b63fc.firebasestorage.app',
    iosBundleId: 'com.example.foodcal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHKmrukjgVAd5lM2smEdmGqSl-RtOcA2U',
    appId: '1:686491556501:ios:05e59c92165a8de814999c',
    messagingSenderId: '686491556501',
    projectId: 'foodcal-b63fc',
    storageBucket: 'foodcal-b63fc.firebasestorage.app',
    iosBundleId: 'com.example.foodcal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmLnlJig_nx0ihDAgmvChclKJinQk1gFo',
    appId: '1:686491556501:web:bbe68fd3158ba69114999c',
    messagingSenderId: '686491556501',
    projectId: 'foodcal-b63fc',
    authDomain: 'foodcal-b63fc.firebaseapp.com',
    storageBucket: 'foodcal-b63fc.firebasestorage.app',
    measurementId: 'G-PCDJRSMMKH',
  );
}
